
CREATE PROCEDURE sp_Insert_CATEGORIA_PLATO
    @ID_CATEGORIA_PLATO int, @NOMBRE_CATEGORIA nvarchar
AS
BEGIN
    INSERT INTO CATEGORIA_PLATO (ID_CATEGORIA_PLATO, NOMBRE_CATEGORIA)
    VALUES (@ID_CATEGORIA_PLATO, @NOMBRE_CATEGORIA);
END;

CREATE PROCEDURE sp_Select_CATEGORIA_PLATO
AS
BEGIN
    SELECT ID_CATEGORIA_PLATO, NOMBRE_CATEGORIA
    FROM CATEGORIA_PLATO;
END;

CREATE PROCEDURE sp_Update_CATEGORIA_PLATO
    @ID_CATEGORIA_PLATO int, @NOMBRE_CATEGORIA nvarchar
AS
BEGIN
    UPDATE CATEGORIA_PLATO
    SET NOMBRE_CATEGORIA = @NOMBRE_CATEGORIA
    WHERE ID_CATEGORIA_PLATO = @ID_CATEGORIA_PLATO;
END;

CREATE PROCEDURE sp_Delete_CATEGORIA_PLATO
    @ID_CATEGORIA_PLATO INT
AS
BEGIN
    DELETE FROM CATEGORIA_PLATO
    WHERE ID_CATEGORIA_PLATO = @ID_CATEGORIA_PLATO;
END;

CREATE PROCEDURE sp_Insert_CLIENTE
    @ID_CLIENTE int, @NOMBRE nvarchar, @APELLIDO nvarchar, @DIRECCION nvarchar, @TELEFONO bigint, @CORREO nvarchar
AS
BEGIN
    INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, CORREO)
    VALUES (@ID_CLIENTE, @NOMBRE, @APELLIDO, @DIRECCION, @TELEFONO, @CORREO);
END;

CREATE PROCEDURE sp_Select_CLIENTE
AS
BEGIN
    SELECT ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, CORREO
    FROM CLIENTE;
END;

CREATE PROCEDURE sp_Update_CLIENTE
    @ID_CLIENTE int, @NOMBRE nvarchar, @APELLIDO nvarchar, @DIRECCION nvarchar, @TELEFONO bigint, @CORREO nvarchar
AS
BEGIN
    UPDATE CLIENTE
    SET NOMBRE = @NOMBRE, APELLIDO = @APELLIDO, DIRECCION = @DIRECCION, TELEFONO = @TELEFONO, CORREO = @CORREO
    WHERE ID_CLIENTE = @ID_CLIENTE;
END;

CREATE PROCEDURE sp_Delete_CLIENTE
    @ID_CLIENTE INT
AS
BEGIN
    DELETE FROM CLIENTE
    WHERE ID_CLIENTE = @ID_CLIENTE;
END;

CREATE PROCEDURE sp_Insert_CLIENTE_QUEJA
    @CLIENTE_ID_CLIENTE int, @QUEJA_ID_QUEJA int, @DSCR_QUEJA nvarchar
AS
BEGIN
    INSERT INTO CLIENTE_QUEJA (CLIENTE_ID_CLIENTE, QUEJA_ID_QUEJA, DSCR_QUEJA)
    VALUES (@CLIENTE_ID_CLIENTE, @QUEJA_ID_QUEJA, @DSCR_QUEJA);
END;

CREATE PROCEDURE sp_Select_CLIENTE_QUEJA
AS
BEGIN
    SELECT CLIENTE_ID_CLIENTE, QUEJA_ID_QUEJA, DSCR_QUEJA
    FROM CLIENTE_QUEJA;
END;

CREATE PROCEDURE sp_Update_CLIENTE_QUEJA
    @CLIENTE_ID_CLIENTE int, @QUEJA_ID_QUEJA int, @DSCR_QUEJA nvarchar
AS
BEGIN
    UPDATE CLIENTE_QUEJA
    SET QUEJA_ID_QUEJA = @QUEJA_ID_QUEJA, DSCR_QUEJA = @DSCR_QUEJA
    WHERE CLIENTE_ID_CLIENTE = @CLIENTE_ID_CLIENTE;
END;

CREATE PROCEDURE sp_Delete_CLIENTE_QUEJA
    @CLIENTE_ID_CLIENTE INT
AS
BEGIN
    DELETE FROM CLIENTE_QUEJA
    WHERE CLIENTE_ID_CLIENTE = @CLIENTE_ID_CLIENTE;
END;

CREATE PROCEDURE sp_Insert_COMPRA
    @ID_COMPRA int, @FECHA_COMPRA date, @MONTO_TOTAL decimal, @DETALLE_COMPRA nvarchar
AS
BEGIN
    INSERT INTO COMPRA (ID_COMPRA, FECHA_COMPRA, MONTO_TOTAL, DETALLE_COMPRA)
    VALUES (@ID_COMPRA, @FECHA_COMPRA, @MONTO_TOTAL, @DETALLE_COMPRA);
END;

CREATE PROCEDURE sp_Select_COMPRA
AS
BEGIN
    SELECT ID_COMPRA, FECHA_COMPRA, MONTO_TOTAL, DETALLE_COMPRA
    FROM COMPRA;
END;

CREATE PROCEDURE sp_Update_COMPRA
    @ID_COMPRA int, @FECHA_COMPRA date, @MONTO_TOTAL decimal, @DETALLE_COMPRA nvarchar
AS
BEGIN
    UPDATE COMPRA
    SET FECHA_COMPRA = @FECHA_COMPRA, MONTO_TOTAL = @MONTO_TOTAL, DETALLE_COMPRA = @DETALLE_COMPRA
    WHERE ID_COMPRA = @ID_COMPRA;
END;

CREATE PROCEDURE sp_Delete_COMPRA
    @ID_COMPRA INT
AS
BEGIN
    DELETE FROM COMPRA
    WHERE ID_COMPRA = @ID_COMPRA;
END;

CREATE PROCEDURE sp_Insert_DETALLE_FACTURA
    @ID_DETALLE_FACTURA int, @FACTURA_ID_FACTURA int, @CANTIDAD_PRODUCTO int, @PRECIO_UNITARIO decimal, @TOTAL decimal
AS
BEGIN
    INSERT INTO DETALLE_FACTURA (ID_DETALLE_FACTURA, FACTURA_ID_FACTURA, CANTIDAD_PRODUCTO, PRECIO_UNITARIO, TOTAL)
    VALUES (@ID_DETALLE_FACTURA, @FACTURA_ID_FACTURA, @CANTIDAD_PRODUCTO, @PRECIO_UNITARIO, @TOTAL);
END;

CREATE PROCEDURE sp_Select_DETALLE_FACTURA
AS
BEGIN
    SELECT ID_DETALLE_FACTURA, FACTURA_ID_FACTURA, CANTIDAD_PRODUCTO, PRECIO_UNITARIO, TOTAL
    FROM DETALLE_FACTURA;
END;

CREATE PROCEDURE sp_Update_DETALLE_FACTURA
    @ID_DETALLE_FACTURA int, @FACTURA_ID_FACTURA int, @CANTIDAD_PRODUCTO int, @PRECIO_UNITARIO decimal, @TOTAL decimal
AS
BEGIN
    UPDATE DETALLE_FACTURA
    SET FACTURA_ID_FACTURA = @FACTURA_ID_FACTURA, CANTIDAD_PRODUCTO = @CANTIDAD_PRODUCTO, PRECIO_UNITARIO = @PRECIO_UNITARIO, TOTAL = @TOTAL
    WHERE ID_DETALLE_FACTURA = @ID_DETALLE_FACTURA;
END;

CREATE PROCEDURE sp_Delete_DETALLE_FACTURA
    @ID_DETALLE_FACTURA INT
AS
BEGIN
    DELETE FROM DETALLE_FACTURA
    WHERE ID_DETALLE_FACTURA = @ID_DETALLE_FACTURA;
END;

CREATE PROCEDURE sp_Insert_EMPLEADO
    @ID_EMPLEADO int, @NOM_EMPLEADO nvarchar, @CARGO_EMPLEADO nvarchar, @TEL_EMPLEADO bigint, @DIR_EMPLEADO nvarchar, @EMAIL_EMPLEADO nvarchar
AS
BEGIN
    INSERT INTO EMPLEADO (ID_EMPLEADO, NOM_EMPLEADO, CARGO_EMPLEADO, TEL_EMPLEADO, DIR_EMPLEADO, EMAIL_EMPLEADO)
    VALUES (@ID_EMPLEADO, @NOM_EMPLEADO, @CARGO_EMPLEADO, @TEL_EMPLEADO, @DIR_EMPLEADO, @EMAIL_EMPLEADO);
END;

CREATE PROCEDURE sp_Select_EMPLEADO
AS
BEGIN
    SELECT ID_EMPLEADO, NOM_EMPLEADO, CARGO_EMPLEADO, TEL_EMPLEADO, DIR_EMPLEADO, EMAIL_EMPLEADO
    FROM EMPLEADO;
END;

CREATE PROCEDURE sp_Update_EMPLEADO
    @ID_EMPLEADO int, @NOM_EMPLEADO nvarchar, @CARGO_EMPLEADO nvarchar, @TEL_EMPLEADO bigint, @DIR_EMPLEADO nvarchar, @EMAIL_EMPLEADO nvarchar
AS
BEGIN
    UPDATE EMPLEADO
    SET NOM_EMPLEADO = @NOM_EMPLEADO, CARGO_EMPLEADO = @CARGO_EMPLEADO, TEL_EMPLEADO = @TEL_EMPLEADO, DIR_EMPLEADO = @DIR_EMPLEADO, EMAIL_EMPLEADO = @EMAIL_EMPLEADO
    WHERE ID_EMPLEADO = @ID_EMPLEADO;
END;

CREATE PROCEDURE sp_Delete_EMPLEADO
    @ID_EMPLEADO INT
AS
BEGIN
    DELETE FROM EMPLEADO
    WHERE ID_EMPLEADO = @ID_EMPLEADO;
END;

CREATE PROCEDURE sp_Insert_FACTURA
    @ID_FACTURA int, @ORDEN_ID_ORDEN int, @FECHA_FACTURA date, @ESTADO_PAGO nvarchar
AS
BEGIN
    INSERT INTO FACTURA (ID_FACTURA, ORDEN_ID_ORDEN, FECHA_FACTURA, ESTADO_PAGO)
    VALUES (@ID_FACTURA, @ORDEN_ID_ORDEN, @FECHA_FACTURA, @ESTADO_PAGO);
END;

CREATE PROCEDURE sp_Select_FACTURA
AS
BEGIN
    SELECT ID_FACTURA, ORDEN_ID_ORDEN, FECHA_FACTURA, ESTADO_PAGO
    FROM FACTURA;
END;

CREATE PROCEDURE sp_Update_FACTURA
    @ID_FACTURA int, @ORDEN_ID_ORDEN int, @FECHA_FACTURA date, @ESTADO_PAGO nvarchar
AS
BEGIN
    UPDATE FACTURA
    SET ORDEN_ID_ORDEN = @ORDEN_ID_ORDEN, FECHA_FACTURA = @FECHA_FACTURA, ESTADO_PAGO = @ESTADO_PAGO
    WHERE ID_FACTURA = @ID_FACTURA;
END;

CREATE PROCEDURE sp_Delete_FACTURA
    @ID_FACTURA INT
AS
BEGIN
    DELETE FROM FACTURA
    WHERE ID_FACTURA = @ID_FACTURA;
END;

CREATE PROCEDURE sp_Insert_INGREDIENTES
    @ID_INGREDIENTES int, @COMPRA_ID_COMPRA int, @NOM_INGREDIENTE nvarchar, @TIPO_INGREDIENTE nvarchar
AS
BEGIN
    INSERT INTO INGREDIENTES (ID_INGREDIENTES, COMPRA_ID_COMPRA, NOM_INGREDIENTE, TIPO_INGREDIENTE)
    VALUES (@ID_INGREDIENTES, @COMPRA_ID_COMPRA, @NOM_INGREDIENTE, @TIPO_INGREDIENTE);
END;

CREATE PROCEDURE sp_Select_INGREDIENTES
AS
BEGIN
    SELECT ID_INGREDIENTES, COMPRA_ID_COMPRA, NOM_INGREDIENTE, TIPO_INGREDIENTE
    FROM INGREDIENTES;
END;

CREATE PROCEDURE sp_Update_INGREDIENTES
    @ID_INGREDIENTES int, @COMPRA_ID_COMPRA int, @NOM_INGREDIENTE nvarchar, @TIPO_INGREDIENTE nvarchar
AS
BEGIN
    UPDATE INGREDIENTES
    SET COMPRA_ID_COMPRA = @COMPRA_ID_COMPRA, NOM_INGREDIENTE = @NOM_INGREDIENTE, TIPO_INGREDIENTE = @TIPO_INGREDIENTE
    WHERE ID_INGREDIENTES = @ID_INGREDIENTES;
END;

CREATE PROCEDURE sp_Delete_INGREDIENTES
    @ID_INGREDIENTES INT
AS
BEGIN
    DELETE FROM INGREDIENTES
    WHERE ID_INGREDIENTES = @ID_INGREDIENTES;
END;

CREATE PROCEDURE sp_Insert_MESA
    @ID_MESA int, @EMPLEADO_ID_EMPLEADO int, @CAPACIDAD int, @DISPONIBILIDAD int, @RESERVABLE nvarchar
AS
BEGIN
    INSERT INTO MESA (ID_MESA, EMPLEADO_ID_EMPLEADO, CAPACIDAD, DISPONIBILIDAD, RESERVABLE)
    VALUES (@ID_MESA, @EMPLEADO_ID_EMPLEADO, @CAPACIDAD, @DISPONIBILIDAD, @RESERVABLE);
END;

CREATE PROCEDURE sp_Select_MESA
AS
BEGIN
    SELECT ID_MESA, EMPLEADO_ID_EMPLEADO, CAPACIDAD, DISPONIBILIDAD, RESERVABLE
    FROM MESA;
END;

CREATE PROCEDURE sp_Update_MESA
    @ID_MESA int, @EMPLEADO_ID_EMPLEADO int, @CAPACIDAD int, @DISPONIBILIDAD int, @RESERVABLE nvarchar
AS
BEGIN
    UPDATE MESA
    SET EMPLEADO_ID_EMPLEADO = @EMPLEADO_ID_EMPLEADO, CAPACIDAD = @CAPACIDAD, DISPONIBILIDAD = @DISPONIBILIDAD, RESERVABLE = @RESERVABLE
    WHERE ID_MESA = @ID_MESA;
END;

CREATE PROCEDURE sp_Delete_MESA
    @ID_MESA INT
AS
BEGIN
    DELETE FROM MESA
    WHERE ID_MESA = @ID_MESA;
END;

CREATE PROCEDURE sp_Insert_ORDEN
    @ID_ORDEN int, @EMPLEADO_ID_EMPLEADO int, @MESA_ID_MESA int, @CLIENTE_ID_CLIENTE int, @ESTADO_ORDEN int, @FECHA_ORDEN date, @TOTAL_PAGAR decimal
AS
BEGIN
    INSERT INTO ORDEN (ID_ORDEN, EMPLEADO_ID_EMPLEADO, MESA_ID_MESA, CLIENTE_ID_CLIENTE, ESTADO_ORDEN, FECHA_ORDEN, TOTAL_PAGAR)
    VALUES (@ID_ORDEN, @EMPLEADO_ID_EMPLEADO, @MESA_ID_MESA, @CLIENTE_ID_CLIENTE, @ESTADO_ORDEN, @FECHA_ORDEN, @TOTAL_PAGAR);
END;

CREATE PROCEDURE sp_Select_ORDEN
AS
BEGIN
    SELECT ID_ORDEN, EMPLEADO_ID_EMPLEADO, MESA_ID_MESA, CLIENTE_ID_CLIENTE, ESTADO_ORDEN, FECHA_ORDEN, TOTAL_PAGAR
    FROM ORDEN;
END;

CREATE PROCEDURE sp_Update_ORDEN
    @ID_ORDEN int, @EMPLEADO_ID_EMPLEADO int, @MESA_ID_MESA int, @CLIENTE_ID_CLIENTE int, @ESTADO_ORDEN int, @FECHA_ORDEN date, @TOTAL_PAGAR decimal
AS
BEGIN
    UPDATE ORDEN
    SET EMPLEADO_ID_EMPLEADO = @EMPLEADO_ID_EMPLEADO, MESA_ID_MESA = @MESA_ID_MESA, CLIENTE_ID_CLIENTE = @CLIENTE_ID_CLIENTE, ESTADO_ORDEN = @ESTADO_ORDEN, FECHA_ORDEN = @FECHA_ORDEN, TOTAL_PAGAR = @TOTAL_PAGAR
    WHERE ID_ORDEN = @ID_ORDEN;
END;

CREATE PROCEDURE sp_Delete_ORDEN
    @ID_ORDEN INT
AS
BEGIN
    DELETE FROM ORDEN
    WHERE ID_ORDEN = @ID_ORDEN;
END;

CREATE PROCEDURE sp_Insert_PAGO
    @ID_PAGO int, @CLIENTE_ID_CLIENTE int, @METODO_PAGO nvarchar, @FECHA_PAGO date
AS
BEGIN
    INSERT INTO PAGO (ID_PAGO, CLIENTE_ID_CLIENTE, METODO_PAGO, FECHA_PAGO)
    VALUES (@ID_PAGO, @CLIENTE_ID_CLIENTE, @METODO_PAGO, @FECHA_PAGO);
END;

CREATE PROCEDURE sp_Select_PAGO
AS
BEGIN
    SELECT ID_PAGO, CLIENTE_ID_CLIENTE, METODO_PAGO, FECHA_PAGO
    FROM PAGO;
END;

CREATE PROCEDURE sp_Update_PAGO
    @ID_PAGO int, @CLIENTE_ID_CLIENTE int, @METODO_PAGO nvarchar, @FECHA_PAGO date
AS
BEGIN
    UPDATE PAGO
    SET CLIENTE_ID_CLIENTE = @CLIENTE_ID_CLIENTE, METODO_PAGO = @METODO_PAGO, FECHA_PAGO = @FECHA_PAGO
    WHERE ID_PAGO = @ID_PAGO;
END;

CREATE PROCEDURE sp_Delete_PAGO
    @ID_PAGO INT
AS
BEGIN
    DELETE FROM PAGO
    WHERE ID_PAGO = @ID_PAGO;
END;

CREATE PROCEDURE sp_Insert_PLATO
    @ID_PLATO int, @CATEGORIA_ID_CATEGORIA_PLATO int, @NOMBRE_PLATO nvarchar, @DESCRIPCION_PLATO nvarchar, @PRECIO_PLATO decimal
AS
BEGIN
    INSERT INTO PLATO (ID_PLATO, CATEGORIA_ID_CATEGORIA_PLATO, NOMBRE_PLATO, DESCRIPCION_PLATO, PRECIO_PLATO)
    VALUES (@ID_PLATO, @CATEGORIA_ID_CATEGORIA_PLATO, @NOMBRE_PLATO, @DESCRIPCION_PLATO, @PRECIO_PLATO);
END;

CREATE PROCEDURE sp_Select_PLATO
AS
BEGIN
    SELECT ID_PLATO, CATEGORIA_ID_CATEGORIA_PLATO, NOMBRE_PLATO, DESCRIPCION_PLATO, PRECIO_PLATO
    FROM PLATO;
END;

CREATE PROCEDURE sp_Update_PLATO
    @ID_PLATO int, @CATEGORIA_ID_CATEGORIA_PLATO int, @NOMBRE_PLATO nvarchar, @DESCRIPCION_PLATO nvarchar, @PRECIO_PLATO decimal
AS
BEGIN
    UPDATE PLATO
    SET CATEGORIA_ID_CATEGORIA_PLATO = @CATEGORIA_ID_CATEGORIA_PLATO, NOMBRE_PLATO = @NOMBRE_PLATO, DESCRIPCION_PLATO = @DESCRIPCION_PLATO, PRECIO_PLATO = @PRECIO_PLATO
    WHERE ID_PLATO = @ID_PLATO;
END;

CREATE PROCEDURE sp_Delete_PLATO
    @ID_PLATO INT
AS
BEGIN
    DELETE FROM PLATO
    WHERE ID_PLATO = @ID_PLATO;
END;

CREATE PROCEDURE sp_Insert_PLATO_INGREDIENTES
    @PLATO_ID_PLATO int, @INGREDIENTES_ID_INGREDIENTES int, @CANTIDAD int
AS
BEGIN
    INSERT INTO PLATO_INGREDIENTES (PLATO_ID_PLATO, INGREDIENTES_ID_INGREDIENTES, CANTIDAD)
    VALUES (@PLATO_ID_PLATO, @INGREDIENTES_ID_INGREDIENTES, @CANTIDAD);
END;

CREATE PROCEDURE sp_Select_PLATO_INGREDIENTES
AS
BEGIN
    SELECT PLATO_ID_PLATO, INGREDIENTES_ID_INGREDIENTES, CANTIDAD
    FROM PLATO_INGREDIENTES;
END;

CREATE PROCEDURE sp_Update_PLATO_INGREDIENTES
    @PLATO_ID_PLATO int, @INGREDIENTES_ID_INGREDIENTES int, @CANTIDAD int
AS
BEGIN
    UPDATE PLATO_INGREDIENTES
    SET INGREDIENTES_ID_INGREDIENTES = @INGREDIENTES_ID_INGREDIENTES, CANTIDAD = @CANTIDAD
    WHERE PLATO_ID_PLATO = @PLATO_ID_PLATO;
END;

CREATE PROCEDURE sp_Delete_PLATO_INGREDIENTES
    @PLATO_ID_PLATO INT
AS
BEGIN
    DELETE FROM PLATO_INGREDIENTES
    WHERE PLATO_ID_PLATO = @PLATO_ID_PLATO;
END;

CREATE PROCEDURE sp_Insert_PLATO_ORDEN
    @PLATO_ID_PLATO int, @ORDEN_ID_ORDEN int, @CANTIDAD int
AS
BEGIN
    INSERT INTO PLATO_ORDEN (PLATO_ID_PLATO, ORDEN_ID_ORDEN, CANTIDAD)
    VALUES (@PLATO_ID_PLATO, @ORDEN_ID_ORDEN, @CANTIDAD);
END;

CREATE PROCEDURE sp_Select_PLATO_ORDEN
AS
BEGIN
    SELECT PLATO_ID_PLATO, ORDEN_ID_ORDEN, CANTIDAD
    FROM PLATO_ORDEN;
END;

CREATE PROCEDURE sp_Update_PLATO_ORDEN
    @PLATO_ID_PLATO int, @ORDEN_ID_ORDEN int, @CANTIDAD int
AS
BEGIN
    UPDATE PLATO_ORDEN
    SET ORDEN_ID_ORDEN = @ORDEN_ID_ORDEN, CANTIDAD = @CANTIDAD
    WHERE PLATO_ID_PLATO = @PLATO_ID_PLATO;
END;

CREATE PROCEDURE sp_Delete_PLATO_ORDEN
    @PLATO_ID_PLATO INT
AS
BEGIN
    DELETE FROM PLATO_ORDEN
    WHERE PLATO_ID_PLATO = @PLATO_ID_PLATO;
END;

CREATE PROCEDURE sp_Insert_PROVEEDOR
    @ID_PROVEEDOR int, @COMPRA_ID_COMPRA int, @NOM_PROVEEDOR nvarchar, @TEL_PROVEEDOR bigint, @DIR_PROVEEDOR nvarchar
AS
BEGIN
    INSERT INTO PROVEEDOR (ID_PROVEEDOR, COMPRA_ID_COMPRA, NOM_PROVEEDOR, TEL_PROVEEDOR, DIR_PROVEEDOR)
    VALUES (@ID_PROVEEDOR, @COMPRA_ID_COMPRA, @NOM_PROVEEDOR, @TEL_PROVEEDOR, @DIR_PROVEEDOR);
END;

CREATE PROCEDURE sp_Select_PROVEEDOR
AS
BEGIN
    SELECT ID_PROVEEDOR, COMPRA_ID_COMPRA, NOM_PROVEEDOR, TEL_PROVEEDOR, DIR_PROVEEDOR
    FROM PROVEEDOR;
END;

CREATE PROCEDURE sp_Update_PROVEEDOR
    @ID_PROVEEDOR int, @COMPRA_ID_COMPRA int, @NOM_PROVEEDOR nvarchar, @TEL_PROVEEDOR bigint, @DIR_PROVEEDOR nvarchar
AS
BEGIN
    UPDATE PROVEEDOR
    SET COMPRA_ID_COMPRA = @COMPRA_ID_COMPRA, NOM_PROVEEDOR = @NOM_PROVEEDOR, TEL_PROVEEDOR = @TEL_PROVEEDOR, DIR_PROVEEDOR = @DIR_PROVEEDOR
    WHERE ID_PROVEEDOR = @ID_PROVEEDOR;
END;

CREATE PROCEDURE sp_Delete_PROVEEDOR
    @ID_PROVEEDOR INT
AS
BEGIN
    DELETE FROM PROVEEDOR
    WHERE ID_PROVEEDOR = @ID_PROVEEDOR;
END;

CREATE PROCEDURE sp_Insert_QUEJA
    @ID_QUEJA int, @FECHA_QUEJA date
AS
BEGIN
    INSERT INTO QUEJA (ID_QUEJA, FECHA_QUEJA)
    VALUES (@ID_QUEJA, @FECHA_QUEJA);
END;

CREATE PROCEDURE sp_Select_QUEJA
AS
BEGIN
    SELECT ID_QUEJA, FECHA_QUEJA
    FROM QUEJA;
END;

CREATE PROCEDURE sp_Update_QUEJA
    @ID_QUEJA int, @FECHA_QUEJA date
AS
BEGIN
    UPDATE QUEJA
    SET FECHA_QUEJA = @FECHA_QUEJA
    WHERE ID_QUEJA = @ID_QUEJA;
END;

CREATE PROCEDURE sp_Delete_QUEJA
    @ID_QUEJA INT
AS
BEGIN
    DELETE FROM QUEJA
    WHERE ID_QUEJA = @ID_QUEJA;
END;

CREATE PROCEDURE sp_Insert_RESERVACION
    @ID_RESERVACION int, @MESA_ID_MESA int, @CLIENTE_ID_CLIENTE int, @COMENSALES int, @FECHA_RESERVACION date
AS
BEGIN
    INSERT INTO RESERVACION (ID_RESERVACION, MESA_ID_MESA, CLIENTE_ID_CLIENTE, COMENSALES, FECHA_RESERVACION)
    VALUES (@ID_RESERVACION, @MESA_ID_MESA, @CLIENTE_ID_CLIENTE, @COMENSALES, @FECHA_RESERVACION);
END;

CREATE PROCEDURE sp_Select_RESERVACION
AS
BEGIN
    SELECT ID_RESERVACION, MESA_ID_MESA, CLIENTE_ID_CLIENTE, COMENSALES, FECHA_RESERVACION
    FROM RESERVACION;
END;

CREATE PROCEDURE sp_Update_RESERVACION
    @ID_RESERVACION int, @MESA_ID_MESA int, @CLIENTE_ID_CLIENTE int, @COMENSALES int, @FECHA_RESERVACION date
AS
BEGIN
    UPDATE RESERVACION
    SET MESA_ID_MESA = @MESA_ID_MESA, CLIENTE_ID_CLIENTE = @CLIENTE_ID_CLIENTE, COMENSALES = @COMENSALES, FECHA_RESERVACION = @FECHA_RESERVACION
    WHERE ID_RESERVACION = @ID_RESERVACION;
END;

CREATE PROCEDURE sp_Delete_RESERVACION
    @ID_RESERVACION INT
AS
BEGIN
    DELETE FROM RESERVACION
    WHERE ID_RESERVACION = @ID_RESERVACION;
END;
